package com.example.APIRollTheDice.Enum;
public enum WSMessageTypes {

    // GAME
    PLAYER_JOINED,
    PLAYER_LEFT,
    CREATED_GAME,
    DELETED_GAME,
    UPDATED_GAME,

    // TOKEN
    TOKEN_MOVE,
    TOKEN_PLACE,
    TOKEN_REMOVE,

    // CHAT
    CHAT_MESSAGE,
    UPDATED_MESSAGE,
    DELETED_MESSAGE,
    CREATE_CHANNEL,
    UPDATE_CHANNEL,
    DELETE_CHANNEL,

    // PRIVATE
    PRIVATE_MESSAGE,
    UPDATE_PRIVATE_MESSAGE,
    DELETE_PRIVATE_MESSAGE,


    // AGENDA
    AGENDA_CREATE,
    AGENDA_UPDATE,
    AGENDA_DELETE,
    AGENDA_REMINDER,

    // SYSTEM / NOTIF
    NOTIFICATION,
    CLEAR_NOTIFICATIONS,
}